name: somethin
favicon: null
layout_spectrum: 0.3763748381752521
typography_spectrum: 0.1775605643633753
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
  brandStrength: 0.3529446416068822
  lightness: 0.481163932941854
  saturation: 0.32888527936302125
  rhythmicContrast: 0.7068092084955424
purpose: []
